# Generated by Django 4.2 on 2023-04-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=100)),
                ('vaqt', models.DateField()),
                ('batafsil', models.TextField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
